# Site Configuration

# Theme, mapped to the directory: ./theme/xxxx
theme: default

# HTML Language setting
lang: "en"

# Plugins, implemented in ./plugins/PLUGIN_NAME
# Use {{ vars.PLUGIN_NAME }} in the settings below

# The output of the plugin can be used below, e.g., {{vars.MediumFollowersCountPlugin}}
plugins:
  # Automatically fetch Github repo star count
  - GithubRepoStarsCountPlugin:
      - ChargePi/ChargePi-go
      - xBlaz3kx/DevX
      - xBlaz3kx/Ender3V2VoronAfterburnerMod

# Google Analytics tracking id
google_analytics_id:

# HTML Title
title: "Blaž's Links"

# Avatar image path
avatar: "https://avatars.githubusercontent.com/u/22869613?s=400&u=ec01a389922f93122327afd5bc946c7d4c70d2f4&v=4"

# Name section text
name: "Blaž Dular"

# Tagline section text
tagline: >-
  A DevOps/Backend engineer with a passion for eMobility, finance and open-source software.

# List of links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# text: The displayed text for the link
# title: The url title
# url: The URL of the link
# alt: Alternative text for accessibility
# target: `_blank` opens in a new tab, `_self` opens in the same frame
links:
  - link:
      icon: "fa-solid fa-rss"
      text: "Website"
      url: "https://blazdular.cc/"
      alt: "Blaž's Website"
      title: "Website"
      target: "_blank"


# List of social media links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# title: The url title
# url: The URL of the social media link
# alt: Alternative text for accessibility
# target: _blank opens in a new tab, _self opens in the same frame
socials:
  - social:
      icon: "fa-brands fa-github"
      url: "https://github.com/xBlaz3kx"
      title: "GitHub"
      alt: "GitHub"
      target: "_blank"
  - social:
      icon: "fa-brands fa-github"
      url: "https://github.com/ChargePi"
      title: "ChargePi's GitHub"
      alt: "ChargePi GitHub"
      target: "_blank"
  - social:
      icon: "fa-brands fa-linkedin"
      url: "https://www.linkedin.com/in/blazdular/"
      title: "LinkedIn"
      alt: "LinkedIn"
      target: "_blank"

# Footer text
footer: >
  Feel free to reach out. Let's connect and make something great together!

# Footer copyright message
# Linkyee is a 100% free, open-source project—feel free to modify the copyright message as you like. :)
copyright: >
  © 2025  <a href="https://blazdular.cc" target="_blank">xBlaz3kx</a>. Powered by <a href="https://github.com/ZhgChgLi/linkyee" target="_blank">linkyee</a>
